In [5]:
#integration
from scipy.integrate import quad

def integrateFunction(x):
    return x

quad(integrateFunction,0,5)

(12.5, 1.3877787807814457e-13)

In [6]:
#double integral
import scipy.integrate as integrate

In [18]:
def f(x,y):
    return x+y

integrate.dblquad(f,0,1,lambda x:0,lambda x:2)

(3.0, 4.436070580899685e-14)

In [23]:
#optimization
import numpy as np
from scipy.optimize import root

In [24]:
def rootfunc(x):
    return x+3.5*np.cos(x)

In [29]:
rootvalue = root(rootfunc,0.3)
rootvalue

    fjac: array([[-1.]])
     fun: array([0.])
 message: 'The solution converged.'
    nfev: 14
     qtf: array([-8.32889313e-13])
       r: array([-4.28198145])
  status: 1
 success: True
       x: array([-1.21597614])

In [33]:
from scipy import linalg
matrix = np.array([[10,4],[2,4]])
matrix

array([[10,  4],
       [ 2,  4]])

In [34]:
inver = linalg.inv(matrix)
inver

array([[ 0.125 , -0.125 ],
       [-0.0625,  0.3125]])

In [35]:
linalg.det(matrix)

32.0

In [38]:
xarr = np.array([[1,1,1],[2,3,4],[2,1,2]])
yarr = np.array([4,12,6])
linalg.solve(xarr,yarr)

array([1., 2., 1.])

In [39]:
#singular value decomposition
svdarr = np.array([[3,5,1],[9,5,7]])
linalg.svd(svdarr)

(array([[-0.37879831, -0.92547925],
        [-0.92547925,  0.37879831]]),
 array([13.38464336,  3.29413449]),
 array([[-0.7072066 , -0.4872291 , -0.51231496],
        [ 0.19208294, -0.82977932,  0.52399467],
        [-0.68041382,  0.27216553,  0.68041382]]))